### ISSUE TITLE
BUG ProductDataExtension - getActiveDiscount() sorting

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-foxy-discounts#14]
**Describe the bug**
Now that we've added support for Amount in addition to Percent, we need to update the `getActiveDiscount()` method in `ProductDataExtension` to sort by type. For example - if `$Discount->Type == 'Percent'`, then discounts should be sorted by `Percent DESC`. If `$Discount->Type == 'Amount'`, then sort by `Amount DESC`.

The purpose of the sorting is to ensure the customer gets the largest of the active discounts.

**Additional context**
This may be tough to implement, since Discounts could be either type. Might need to query for active Discounts of each type and merge the DataLists.

https://github.com/dynamic/silverstripe-foxy-discounts/blob/master/src/Extension/ProductDataExtension.php#L51

**Comment by muskie9** [comment]
resolved via #16, #17 
resolved via dynamic/silverstripe-foxy#71, dynamic/silverstripe-foxy#72
